apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
data:
  url: {{ quote .Values.elasticsearch.url }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm
data:
  server_url: {{ quote .Values.observability.server_url }}
